name: Default Cluster Templates

on:
  push:
    branches: [ "main" ]
    paths:
        - 'test/**/flux-system/gotk-*.yaml'

  workflow_dispatch:

jobs:
  copy-templates:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push changes
        run: |
          NEW_APP_VERSION="${{ github.sha }}"
          echo "Updating image version to $NEW_APP_VERSION" > ./test/test.txt
          git pull
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config commit.gpgsign true
          git add ./test/
          git commit -m "auto: update default version to $NEW_APP_VERSION" --allow-empty
          git push
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files-dir-names.outputs.added_files }}; do
            echo "$file was added"
          done
          
