name: Default Cluster Templates

on:
  push:
    branches: [ "main" ]
    paths:
        - 'test/**/flux-system/gotk-*.yaml'

  workflow_dispatch:

jobs:
  copy-templates:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: ./test/test.txt
          DESTINATION_BRANCH: main
        run: |
          NEW_APP_VERSION="${{ github.sha }}"
          echo "Updating image version to $NEW_APP_VERSION" > ./test/test.txt
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="auto: update default version to $NEW_APP_VERSION"
          export SHA=$( git rev-parse $DESTINATION_BRANCH:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="$DESTINATION_BRANCH" \
            --field sha="$SHA"
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v35
        with:
          dir_names: "true"

      - name: List all added files
        run: |
          for file in ${{ steps.changed-files-dir-names.outputs.added_files }}; do
            echo "$file was added"
          done
          
